spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    topic:
      btc-price: mockbit
      create-limit-order: limit-orders
      cancel-limit-order: cancel-limit-orders
    key:
      current-price-key: current-price
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mockbit-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      orders-key: Orders
      current-price-key: current-btc-price
      host: localhost
      port: 6379
      password: wlscjf9687!A

  websocket:
    upbit-url: wss://api.upbit.com/websocket/v1

cors:
  max-age: 3600
  allowed-origins: http://localhost:3000

security:
  jwt:
    token:
      secret-key: skdmeejEKJdkDjklDlkj123DKLJ3kDkeDkDKQMEOD1D90D8dE
      expire-length: 604800000 # 1주일

cookie:
  http-only: true
  secure: true
  domain: "localhost"
  path: /
  same-site: "None"
  max-age: 7D